filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["LOGSTASH_HOSTS"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

filebeat.inputs:
- type: log
  enabled: true
  fields:
    servicetype: APPSERVICE
    environment: ENVIRONMENT
  paths:
    - /var/www/html/var/log/*.log
    - /var/log/supervisor/*.log
